name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-2019
    env:
      LIBCLANG_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\Llvm\x64\bin'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v1

      - uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install vulkan-sdk
      
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
    
      - name: Prepare deps
        run: bash ./prepare-deps.sh
      
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      
      - name: Build apk debug project (APK)
        run: ./gradlew assembleDebug

      - name: Upload APK Debug
        uses: actions/upload-artifact@v2
        with:
          name: Windows build APK(s) debug generated
          path: app/build/outputs/apk/debug/

  # check-linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: stable
  #         override: true
  #         components: clippy
  #     - uses: Swatinem/rust-cache@v1

  #     - name: Build and install dependencies
  #       env:
  #         RUST_BACKTRACE: 1
  #       run: |
  #         sudo apt update
  #         sudo apt install build-essential pkg-config nasm libva-dev libdrm-dev libvulkan-dev libx264-dev libx265-dev cmake libasound2-dev libjack-jackd2-dev libxrandr-dev libunwind-dev
  #         cargo xtask prepare-deps --platform linux --no-nvidia

  #     - name: Prepare deps
  #       run: bash ./prepare-deps.sh
      
  #     - uses: nttld/setup-ndk@v1
  #       id: setup-ndk
  #       with:
  #         ndk-version: r25c

  #     - name: Set Up JDK
  #       uses: actions/setup-java@v1
  #       with:
  #         java-version: 11
    
  #     - name: Change wrapper permissions
  #       run: chmod +x ./gradlew
      
  #     - name: Build apk debug project (APK)
  #       run: ./gradlew assembleDebug

  #     - name: Upload APK Debug
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: Linux build APK(s) debug generated
  #         path: app/build/outputs/apk/debug/